config:
  burrito:
    runner:
      image:
        repository: burrito
        tag: "1756136181"
        pullPolicy: Never
    datastore:
      storage:
        mock: true
global:
  deployment:
    image:
      repository: burrito
      tag: "1756136181"
      pullPolicy: Never
tenants:
  - namespace:
      create: true
      name: "burrito-project"
