apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controllers
    app.kubernetes.io/name: burrito-controllers
    app.kubernetes.io/part-of: burrito
  name: burrito-controllers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: burrito-controllers
subjects:
  - kind: ServiceAccount
    name: burrito-controllers
    namespace: burrito
